### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by winlee-d** [jiongjiongJOJO/Sign-WenShuShu#16]
您好，按照教程来的，前两天还可以签到成功，后来就运行失败，偶尔运行成功也不能完成签到和推送，红色代码显示exit 什么什么code1

**Comment by jiongjiongJOJO** [comment]
官方增加了验证码验证，等更新或弃坑😜😜😜

**Comment by jiongjiongJOJO** [comment]
暂时停更，不为别的，官方不作为，老是在这种无关紧要的地方搞攻防，好好开发基本功能才是本质，大家肉眼可见的沦落，还不开发些大家感兴趣的东西，是不是很快就没落在历史的洪流了呢？？因为被支付宝拉黑就放弃了挣扎还是说支付宝只是个契机，本来就像摆烂，刚好支付宝给了个借口？
大家关注的承诺：
webdav？![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/1dfcfe55-3e09-4566-8e0f-c9ce557a94c9)
共享盘权限管理？
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/a145392e-b692-4e21-bd0c-0f95d8217ec5)
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/475f4606-a7ff-4881-a744-926cbc9a7b52)
无关紧要的承诺：
用户数？VIP和普通用户一样？
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/eb9d8647-cc61-4d47-98d1-321e6b959045)
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/49a05641-d86d-4f28-9cf5-7f8b3be4dd12)
定时？
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/70c4f6d2-d60c-4b5e-be9b-e5f6c2f0336d)
联系人？
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/96b49568-1154-4c2c-ae7c-5a2d444e1730)
官网没说，但QQ群或微信群承诺的：
IOS等等（待更新）

**Comment by jiongjiongJOJO** [comment]
补充一下，虽然不能正常签到了，但是登录功能还是没有加验证码，所以此仓库还是能保证正常登录保活的。
![image](https://github.com/jiongjiongJOJO/Sign-WenShuShu/assets/58727904/b543b1c0-ddef-480e-9aec-181807c95577)

**Comment by winlee-d** [comment]
支持作者✊再次感谢

**Comment by jiongjiongJOJO** [comment]
已修复@winlee-d 。
但，To官方：BDHS！！！用心做点大家关注的东西吧。
